project:
  type: website
  output-dir: docs

website:
  title: "Niger Anticipatory Action: Drought"
  description: "Analysis for drought anticipatory action in Niger."
  navbar:
    background: primary
    title: "Niger Anticipatory Action: Drought"

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    toc-location: left
    embed-resources: true
    fig-cap-location: bottom

execute:
  freeze: auto
  echo: false
  warning: false
  message: false
